# yaml-language-server: $schema=https://www.schemastore.org/pnpm-workspace.json

packages:
  - packages/*

allowBuilds:
  esbuild: true

verifyDepsBeforeRun: false

minimumReleaseAge: 0

overrides:
  vite@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'

catalogMode: prefer

catalog:
  '@types/node': ^26.6.4
  '@vitejs/plugin-react': ^6.1.1
  'oxc-transform-react': ^0.145.0
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: ^5.0.3
