package main

import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"log/slog"
	"math/big"
	"time"
	"uuid"

	"github.com/huandu/go-sqlbuilder"
	"github.com/urfave/cli/v3"

	"github.com/riipandi/saka/database/entity"
	"github.com/riipandi/saka/internal/audit"
	"github.com/riipandi/saka/internal/authz"
	"github.com/riipandi/saka/internal/datastore"
	"github.com/riipandi/saka/modules/identity/password"
	"github.com/riipandi/saka/modules/identity/session"
	"github.com/riipandi/saka/pkg/crypto"
	"github.com/riipandi/saka/pkg/printext"
)

var adminResetPasswordCmd = &cli.Command{
	Name:      "admin:reset-password",
	Usage:     "Replace an administrator's credential",
	ArgsUsage: "EMAIL_ADDRESS",
	Category:  "Deployment commands",
	Description: `Replaces one administrator's password, addressed by email.

The target must hold the administrator role: the recovery of a regular
account's access travels the forgotten-password flow, where proving control
of the address is the credential. This command runs on the server the
database lives on, so the operator's shell access is the proof it stands
for.

--new-password sets the replacement explicitly; without it a random one is
generated and printed exactly once — this terminal is the only place it
exists. The account's live sessions are revoked either way, and the swap,
the revocations, and the audit record commit in one transaction.`,
	Flags: []cli.Flag{
		&cli.StringFlag{
			Name:  "new-password",
			Usage: "The replacement credential (generated when absent)",
		},
	},
	Action: runAdminResetPassword,
}

// runAdminResetPassword replaces one administrator's credential.
//
// The refusals are the safeguards, and there is no override flag: an
// address no account answers, an account that holds no administrator role,
// and an account the deployment has disabled or banned are all refused
// with the reason named. A fresh password is generated by the command and
// printed to this terminal once — it never reaches a log or a flag echo.
func runAdminResetPassword(ctx context.Context, cmd *cli.Command) error {
	cfg, err := configFrom(ctx)
	if err != nil {
		return err
	}

	if err = requireMigrated(ctx, cfg); err != nil {
		return err
	}

	email := cmd.Args().First()
	if email == "" {
		return errors.New("the account's email address is required: saka admin:reset-password EMAIL_ADDRESS")
	}
	proposed := cmd.String("new-password")

	pool, err := openStore(ctx, cfg)
	if err != nil {
		return err
	}
	defer pool.Shutdown(context.Background())

	p := printext.NewPalette(cmd.Root().Writer)
	if reportErr := reportTarget(p, databaseOptions(ctx, cfg).DSN); reportErr != nil {
		return reportErr
	}

	repo := password.NewRepository()
	account, err := repo.FindUserByEmail(ctx, pool, email)
	if errors.Is(err, datastore.ErrNoRows) {
		return fmt.Errorf("no account with address %q", email)
	}
	if err != nil {
		return err
	}
	if account.Disabled {
		return fmt.Errorf("the account %q is disabled; enable it before recovering its access", account.Username)
	}
	if account.BannedNow() {
		return fmt.Errorf("the account %q is banned; the ban is this refusal's answer", account.Username)
	}

	if adminErr := requireAdministrator(ctx, pool, account.ID); adminErr != nil {
		return adminErr
	}

	credential := proposed
	generated := false
	if credential == "" {
		credential, err = generateCredential()
		if err != nil {
			return fmt.Errorf("admin:reset-password: generate credential: %w", err)
		}
		generated = true
	}
	if valErr := password.Validate(credential); valErr != nil {
		return valErr
	}

	hash, err := crypto.NewPasswordHasher().Hash(credential)
	if err != nil {
		return fmt.Errorf("admin:reset-password: hash credential: %w", err)
	}

	recorder := audit.NewRecorder(slog.New(slog.DiscardHandler))
	var ended int
	err = pool.WithTx(ctx, func(ctx context.Context, tx datastore.Querier) error {
		// The sessions die with the credential they were minted against —
		// the same rule the forgotten-password flow keeps — and the swap,
		// the revocations, and the record commit together. The ender is
		// recorded as the account itself, the way the ban's revocation is:
		// the sessions did nothing wrong, the credential changed.
		rows, revokeErr := session.NewRepository().RevokeLiveForUser(ctx, tx, account.ID, nil, account.ID, time.Now())
		if revokeErr != nil {
			return revokeErr
		}
		ended = len(rows)
		if setErr := repo.SetPasswordHash(ctx, tx, account.ID, hash); setErr != nil {
			return setErr
		}
		recorder.Record(ctx, tx, audit.Entry{
			Event:  audit.EventPasswordReset,
			Status: audit.StatusSuccess,
			UserID: account.ID.String(),
			Payload: map[string]string{
				"username": account.Username,
				"source":   "admin_reset_password",
				"sessions": fmt.Sprint(ended),
			},
		})
		return nil
	})
	if err != nil {
		return err
	}

	_, err = fmt.Fprintf(p.Writer(), "credential replaced for %s <%s>; %s revoked\n",
		account.Username, account.Email, printext.Plural(ended, "session"))
	if err != nil {
		return err
	}
	if generated {
		_, err = fmt.Fprintf(p.Writer(), "\n%s\n\n(the generated credential — store it now; it is not recoverable)\n", credential)
		if err != nil {
			return err
		}
	}
	return printStatusLine(p, "password reset")
}

// requireAdministrator refuses an account that holds no active grant of the
// administrator role. The role is the whole of the command's authority: a
// regular account's recovery belongs to the flow that proves the address.
func requireAdministrator(ctx context.Context, db datastore.Querier, userID uuid.UUID) error {
	roleID, err := administratorRoleID(ctx, db)
	if err != nil {
		return err
	}

	sb := sqlbuilder.PostgreSQL.NewSelectBuilder()
	sb.Select("1")
	sb.From(entity.TableUserRoles)
	sb.Where(
		sb.Equal("user_id", userID.String()),
		sb.Equal("role_id", roleID),
		sb.IsNull("revoked_at"),
	)

	query, args := sb.Build()
	var one int
	if err := db.QueryRow(ctx, query, args...).Scan(&one); errors.Is(err, datastore.ErrNoRows) {
		return fmt.Errorf("the account does not hold the %s role; recover a regular account's access through the forgotten-password flow", authz.AdministratorRole)
	} else if err != nil {
		return fmt.Errorf("admin:reset-password: read grants: %w", err)
	}
	return nil
}

// generateCredential draws a password the policy accepts from the crypto
// source: an alphabet without ambiguous characters, at least one of every
// character class the policy counts, long enough to stand as a passphrase.
func generateCredential() (string, error) {
	const (
		lower   = "abcdefghijkmnopqrstuvwxyz"
		upper   = "ABCDEFGHJKLMNPQRSTUVWXYZ"
		digits  = "23456789"
		symbols = "!@#$%^&*-_=+"
		length  = 20
	)
	alphabet := lower + upper + digits + symbols

	draw := func(source string) (byte, error) {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(source))))
		if err != nil {
			return 0, err
		}
		return source[n.Int64()], nil
	}

	out := make([]byte, 0, length)
	for _, class := range []string{lower, upper, digits, symbols} {
		c, err := draw(class)
		if err != nil {
			return "", err
		}
		out = append(out, c)
	}
	for len(out) < length {
		c, err := draw(alphabet)
		if err != nil {
			return "", err
		}
		out = append(out, c)
	}
	// Fisher-Yates over the crypto source, so the guaranteed classes do
	// not sit in the first four positions.
	for i := len(out) - 1; i > 0; i-- {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(i+1)))
		if err != nil {
			return "", err
		}
		j := n.Int64()
		out[i], out[j] = out[j], out[i]
	}
	return string(out), nil
}
