package entity

// TODO: reworks: centralize table name references

const (
	TableAPIKeys                      = "public.api_keys"
	TableAppMigration                 = "public.app_migration"
	TableAppSettings                  = "public.app_settings"
	TableAuditLogs                    = "public.audit_logs"
	TableAuthTokens                   = "public.auth_tokens"
	TableBlocklistEntries             = "public.blocklist_entries"
	TableCustomClaims                 = "public.custom_claims"
	TableDeletedRecords               = "public.deleted_records"
	TableDeviceLoginRequests          = "public.device_login_requests"
	TableJWKS                         = "public.jwks"
	TableKnownDevices                 = "public.known_devices"
	TableMFAPending                   = "public.mfa_pending"
	TableMFARecoveryCodes             = "public.mfa_recovery_codes"
	TableMFATOTP                      = "public.mfa_totp"
	TableNotificationReads            = "public.notification_reads"
	TableNotificationUserGroups       = "public.notification_user_groups"
	TableNotificationUsers            = "public.notification_users"
	TableNotifications                = "public.notifications"
	TableOAuthJtis                    = "public.oauth_jtis"
	TableOAuthSessions                = "public.oauth_sessions"
	TableOIDCClients                  = "public.oidc_clients"
	TableOIDCClientsAllowedUserGroups = "public.oidc_clients_allowed_user_groups"
	TablePermissions                  = "public.permissions"
	TableQueueTasks                   = "public.queue_tasks"
	TableQueueTasksCompleted          = "public.queue_tasks_completed"
	TableRateLimits                   = "public.rate_limits"
	TableRolePermissions              = "public.role_permissions"
	TableRoles                        = "public.roles"
	TableSchedulerJobs                = "public.scheduler_jobs"
	TableScimServiceProviders         = "public.scim_service_providers"
	TableSessions                     = "public.sessions"
	TableSignupTokens                 = "public.signup_tokens"
	TableSignupTokensUserGroups       = "public.signup_tokens_user_groups"
	TableStorageBuckets               = "public.storage_buckets"
	TableStorageObjects               = "public.storage_objects"
	TableUserAuthorizedOIDCClients    = "public.user_authorized_oidc_clients"
	TableUserGroups                   = "public.user_groups"
	TableUserGroupsAllowedOIDCClients = "public.user_groups_allowed_oidc_clients"
	TableUserGroupsUsers              = "public.user_groups_users"
	TableUserPasswords                = "public.user_passwords"
	TableUserPermissions              = "public.user_permissions"
	TableUserRoles                    = "public.user_roles"
	TableUsers                        = "public.users"
	TableWebauthnCredentials          = "public.webauthn_credentials"
	TableWebauthnSessions             = "public.webauthn_sessions"
	TableWebhookDeliveries            = "public.webhook_deliveries"
	TableWebhookDeliveryAttempts      = "public.webhook_delivery_attempts"
	TableWebhookEndpoints             = "public.webhook_endpoints"
)
